{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dpom-mcp-server.serviceAccountName" . }}
  labels:
    {{- include "dpom-mcp-server.labels" . | nindent 4 }}
{{- end }}
